# Generated by Django 5.0.1 on 2024-02-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='Dish',
        #     fields=[
        #         ('idFoodType',models.BigAutoField(auto_created=True, primary_key=True,serialize=False, verbose_name='Dish')),
        #         ('name', models.CharField(max_length=30)),
        #         # ('')
        #     ]
        # )
    ]
