# Generated by Django 5.0.1 on 2024-03-13 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_dish_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pes', models.IntegerField()),
                ('dish', models.ManyToManyField(related_name='Ingredients', to='app.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Calorias', 'Calorias'), ('Proteina', 'Proteina'), ('Grasas', 'Grasas'), ('Carbohidratos', 'Carbohidratos'), ('Sal', 'Sal')], max_length=20, unique=True)),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='app.ingredients')),
            ],
        ),
    ]
