# Generated by Django 5.0.1 on 2024-03-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ingredients_nutrient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='weigth',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='app.ingredients'),
        ),
    ]
