# Generated by Django 5.0.1 on 2024-03-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_dish_weigth_remove_ingredients_dish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Carn', 'Carn'), ('Peix', 'Peix'), ('Ous', 'Ous'), ('Fruita', 'Fruita'), ('Verdura', 'Verdura')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Esmorzar', 'Esmorzar'), ('Dinar', 'Dinar'), ('Berenar', 'Berenar'), ('Sopar', 'Sopar')], max_length=20, unique=True)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='nutrient',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='carbos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='grasa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='protein',
            field=models.FloatField(null=True),
        ),
    ]
