# Generated by Django 5.0.1 on 2024-03-13 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ingredients_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.meal'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.CharField(choices=[('Carn', 'Carn'), ('Peix', 'Peix'), ('Ous', 'Ous'), ('Fruita', 'Fruita'), ('Verdura', 'Verdura'), ('Pasta', 'Pasta')], max_length=20, unique=True),
        ),
    ]
