# Generated by Django 5.0.1 on 2024-03-13 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dish_meal_alter_foodtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='nutrients',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.nutrient'),
        ),
    ]
