# Generated by Django 5.0.1 on 2024-03-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ingredients_nutrients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='pes',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
