# Generated by Django 5.0.1 on 2024-03-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_ingredients_pes_ingredients_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='grasaSAT',
            field=models.FloatField(null=True),
        ),
    ]
