# Generated by Django 5.0.1 on 2024-03-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_nutrient_grasasat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(choices=[('Esmorzar', 'Esmorzar'), ('Dinar', 'Dinar'), ('Berenar', 'Berenar'), ('Sopar', 'Sopar'), ('Altres', 'Altres')], max_length=20, unique=True),
        ),
    ]
