# Generated by Django 5.0.4 on 2024-04-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_meal_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
