# Generated by Django 5.0.6 on 2024-05-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_student_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
