# Generated by Django 5.0.6 on 2024-05-14 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
