# Generated by Django 5.0.6 on 2024-05-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_dish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='grams',
            field=models.IntegerField(default=100),
        ),
    ]
