# Generated by Django 5.0.6 on 2024-05-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_dish_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='time',
        ),
    ]
