# Generated by Django 5.0.4 on 2024-05-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(default=100),
        ),
    ]
