# Generated by Django 5.0.2 on 2024-05-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_dish_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(choices=[('Desayuno', 'Desayuno'), ('Comida', 'Comida'), ('Merienda', 'Merienda'), ('Cena', 'Cena'), ('Otros', 'Otros')], max_length=20, unique=True),
        ),
    ]
